"""add city

Revision ID: a3f664799a1f
Revises: 638e0fca90c6
Create Date: 2025-08-15 19:16:26.460072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f664799a1f'
down_revision: Union[str, Sequence[str], None] = '638e0fca90c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'users', ['city'])
    op.create_unique_constraint(None, 'users', ['country'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
